/**
 * Levels define the permission granted for each user
 *
 * New levels can be added through here
 */
export const levels = {
  USER: 0,
  APPROVER: 1,
  JCRC: 2,
  KEWEB: 3
};

/**
 * Actions define the type of actions available in the system
 *
 * New actions can be added here
 */
export const actions = {
  VIEW_ADMIN_PAGE: 'VIEW_ADMIN_PAGE',
  VIEW_FULL_ADMIN_PAGE: 'VIEW_FULL_ADMIN_PAGE',
  DELETE_BOOKING: 'DELETE_BOOKING',
  FETCH_BOOKING: 'FETCH_BOOKING',
  DELETE_BOOKING_REQUEST: 'DELETE_BOOKING_REQUEST',
  FETCH_BOOKING_REQUEST: 'FETCH_BOOKING_REQUEST',
  MANAGE_BOOKING_REQUEST: 'MANAGE_BOOKING_REQUEST',
  CREATE_RECURRING_BOOKING_REQUEST: 'CREATE_RECURRING_BOOKING_REQUEST',
  CREATE_VENUE: 'CREATE_VENUE',
  EDIT_VENUE: 'EDIT_VENUE',
  DELETE_VENUE: 'DELETE_VENUE',
  CREATE_ANNOUNCEMENT: 'CREATE_ANNOUNCEMENT',
  EDIT_ANNOUNCEMENT: 'EDIT_ANNOUNCEMENT',
  DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',
  FETCH_ALL_CCA: 'FETCH_ALL_CCA',
  FETCH_ALL_CCA_ATTENDANCE: 'FETCH_ALL_CCA_ATTENDANCE',
  OVERRIDE_CREATE_SESSION: 'OVERRIDE_CREATE_SESSION',
  OVERRIDE_EDIT_SESSION: 'OVERRIDE_EDIT_SESSION',
  OVERRIDE_DELETE_SESSION: 'OVERRIDE_DELETE_SESSION',
  POPULATE_CCA_RECORD: 'POPULATE_CCA_RECORD',
  FETCH_USER_CCA_RECORD: 'FETCH_USER_CCA_RECORD',
  FETCH_ALL_KEIPS: 'FETCH_ALL_KEIPS',
  POPULATE_KEIPS: 'POPULATE_KEIPS',
  DELETE_KEIPS: 'DELETE_KEIPS',
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  FETCH_USER_DATA: 'FETCH_USER_DATA',
  POPULATE_USER: 'POPULATE_USER',
  DELETE_LOGS: 'DELETE_LOGS'
};
