/**
 * List of CCA for reference.
 *
 * Not used in the application
 */
export const CCALIST = [
  'acaKE',
  'Amplitude',
  'Badminton F',
  'Badminton M',
  'BandXY',
  'Basketball F',
  'Basketball M',
  'Block Committee AB',
  'Block Committee CD',
  'Block Committee E',
  'Block Committee F',
  'Block Committee GH',
  'Chinese Drama',
  'Choir',
  'Cultural Management Board (CMB)',
  'External Relations Committee (ERC)',
  'Flag Committee',
  'Floorball F',
  'Floorball M',
  'Green Team',
  'Hall Affairs Board (HAB)',
  'Hallplay',
  'Handball F',
  'Handball M',
  'IHG Co-Convening',
  'KE Angels',
  'KE Dance',
  'KE Moonlight',
  'KE Motion',
  'KE Titans',
  'KE Vision',
  'KE Web',
  'KE Welcoming Orientation Camp (KEWOC) Committee',
  'KEVIIing Back',
  'KEnsemble',
  'Merit Awards Board (MAB)',
  'Netball F',
  'OCIP Cambodia',
  'OCIP Laos',
  'RAG Committee',
  'Road Relay F',
  'Road Relay M',
  'Sepak Takraw M',
  'Soccer F',
  'Soccer M',
  'Softball',
  'Sports Management Committee (SMC)',
  'Squash F',
  'Squash M',
  'Swimming F',
  'Swimming M',
  'Table Tennis F',
  'Table Tennis M',
  'Tennis F',
  'Tennis M',
  'The Dream Composition (TDC)',
  'The SOCs',
  'Touch Rugby F',
  'Touch Rugby M',
  'Track & Field F',
  'Track & Field M',
  'Ultimate Frisbee',
  'Volleyball F',
  'Volleyball M',
  'Yearbook'
];
